# Generated by Django 4.2.7 on 2023-12-14 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_employeemodel_managermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeModel',
        ),
        migrations.DeleteModel(
            name='ManagerModel',
        ),
    ]
